// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFggNrJqviwUaPC4DcrMVvT6YAcqOsaJo',
    appId: '1:1051753665163:web:d20133d9298e454755ba8e',
    messagingSenderId: '1051753665163',
    projectId: 'ngobrol-chat-app',
    authDomain: 'ngobrol-chat-app.firebaseapp.com',
    storageBucket: 'ngobrol-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCGcIL8b0bTT_tMinWWb3qRcsqkfp28JQ',
    appId: '1:1051753665163:android:9f5548052f4f928c55ba8e',
    messagingSenderId: '1051753665163',
    projectId: 'ngobrol-chat-app',
    storageBucket: 'ngobrol-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVPO3LfSNozVKFGVKPw-hoy7fDbAFSXj4',
    appId: '1:1051753665163:ios:40275d388bf94cac55ba8e',
    messagingSenderId: '1051753665163',
    projectId: 'ngobrol-chat-app',
    storageBucket: 'ngobrol-chat-app.appspot.com',
    iosBundleId: 'com.example.ngobrolChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVPO3LfSNozVKFGVKPw-hoy7fDbAFSXj4',
    appId: '1:1051753665163:ios:d199477003bcc88955ba8e',
    messagingSenderId: '1051753665163',
    projectId: 'ngobrol-chat-app',
    storageBucket: 'ngobrol-chat-app.appspot.com',
    iosBundleId: 'com.example.ngobrolChatApp.RunnerTests',
  );
}
